name: 'build multi arch manifest from amd64 & arm64 images'
description: 'amd64 & arm64 images to create multi arch manifest for deployment'
inputs:
  version:
    required: true
    type: string
  tag:
    type: string
  amd_tag:
    type: string
  arm_tag:
    type: string
  module:
    type: string 
  registry_login_server:
    required: true
    type: string
  registry_username:
    required: true
    type: string
  registry_password:
    required: true
    type: string  

runs:
    using: "composite"
    steps:
      - name: 'login to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ inputs.registry_login_server }}
          username: ${{ inputs.registry_username }}
          password: ${{ inputs.registry_password }}
        
      - name: Create Latest manifest and push to registry
        shell: bash
        run: |
            docker manifest create iqgeoproddev.azurecr.io/$MODULE:$VERSION \
                iqgeoproddev.azurecr.io/$MODULE:$AMD_TAG \
                iqgeoproddev.azurecr.io/$MODULE:$ARM_TAG
            docker manifest annotate iqgeoproddev.azurecr.io/$MODULE:$VERSION \
                iqgeoproddev.azurecr.io/$MODULE:$AMD_TAG --os linux --arch amd64
            docker manifest annotate iqgeoproddev.azurecr.io/$MODULE:$VERSION \
                iqgeoproddev.azurecr.io/$MODULE:$ARM_TAG --os linux --arch arm64
            docker manifest push iqgeoproddev.azurecr.io/$MODULE:$VERSION
        env:
          VERSION: ${{ inputs.version }}
          AMD_TAG: ${{ inputs.amd_tag }}
          ARM_TAG: ${{ inputs.arm_tag }}
          MODULE: ${{ inputs.module }}
